### ISSUE TITLE
Helo can you please upload the source code as well? It would be very useful for earning my billions thank you, when will you upload your kulfoldi-accent video tutorial about the usage thank you

### ISSUE THREAD

**Issue by andrasmarkus** [csabe812/ionicQReader#1]

**Comment by csabe812** [comment]
Hi @andrasmarkus ,
Thank you for your patience.
I pushed a starter package qrScanner.
Try it with your browser (if you have a webcam), or build an android apk (see Readme.md).
If you have any question do not hasitate to contact with me.
